# Generated by Django 3.2.18 on 2023-06-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=225)),
                ('tanggal_publikasi', models.DateTimeField(auto_now_add=True)),
                ('Deskripsi', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='covers/')),
                ('update', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
        ),
    ]
