# Generated by Django 3.2.18 on 2023-05-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appkemahasiswaan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('NIM', models.IntegerField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('prodi', models.CharField(max_length=60)),
                ('angkatan', models.IntegerField()),
                ('alamat', models.TextField()),
                ('agama', models.TextField(max_length=50)),
                ('no_tlp', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='kegiatan',
            name='image',
            field=models.ImageField(null=True, upload_to='covers/'),
        ),
    ]
