# Generated by Django 3.2.18 on 2023-05-17 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appkemahasiswaan', '0002_auto_20230517_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='agama',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Prestasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('prodi', models.CharField(max_length=50)),
                ('prestasi', models.CharField(max_length=100)),
                ('penyelenggara', models.CharField(max_length=100)),
                ('tanggal', models.DateField()),
                ('tingkat', models.CharField(max_length=50)),
                ('juara', models.IntegerField()),
                ('NIM', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appkemahasiswaan.mahasiswa')),
            ],
        ),
    ]
