# Generated by Django 3.2.18 on 2023-05-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appkemahasiswaan', '0003_auto_20230518_0013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestasi',
            name='id',
        ),
        migrations.AddField(
            model_name='kegiatan',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='kegiatan',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='kegiatan',
            name='judul',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='kegiatan',
            name='tanggal_publikasi',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='prestasi',
            name='NIM',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
