# Generated by Django 3.2.18 on 2023-06-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appkemahasiswaan', '0006_data_beasiswa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_beasiswa',
            name='status',
            field=models.CharField(max_length=200),
        ),
    ]
