# Generated by Django 3.2.18 on 2023-06-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appkemahasiswaan', '0007_alter_data_beasiswa_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='data_beasiswa',
            name='image',
            field=models.ImageField(null=True, upload_to='covers/'),
        ),
    ]
